---
- hosts: servers
  user: ale
  become: True
  gather_facts: no
  tasks:
  - name: Install packages
    apt:
      pkg:
        - openssh-client
        - openssh-server
        - sudo
        - screenfetch
        - linuxlogo
        - vim
        - htop
        - net-tools
        - nginx
        - nodejs
        - npm
      state: present
      update_cache: True
